export const ADD_COMMAND = 'ADD_COMMAND';
export const ADD_ITEM_TO_COMMAND = 'ADD_ITEM_TO_COMMAND';
export const REMOVE_ITEM_TO_COMMAND = 'REMOVE_ITEM_TO_COMMAND';
export const RESET_COMMAND_LIST = 'RESET_COMMAND_LIST';
export const PUSH_COMMAND = 'PUSH_COMMAND';
export const UPDATE_COMMAND = 'UPDATE_COMMAND';
