export const RESET_PLATE_LIST = 'RESET_PLATE_LIST';
export const PUSH_PLATE = 'PUSH_PLATE';
export const UPDATE_PLATE = 'UPDATE_PLATE';
export const ADD_CHOICE_TO_PLATE = 'ADD_CHOICE_TO_PLATE';
export const REMOVE_CHOICE_TO_PLATE = 'REMOVE_CHOICE_TO_PLATE';
export const UPDATE_CHOICE_TO_PLATE = 'UPDATE_CHOICE_TO_PLATE';
