export const ADD_ORDER = 'ADD_ORDER';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const ADD_ITEM_TO_ORDER = 'ADD_ITEM_TO_ORDER';
export const REMOVE_ITEM_TO_ORDER = 'REMOVE_ITEM_TO_ORDER';
export const RESET_ORDER_LIST = 'RESET_ORDER_LIST';
export const UPDATE_ORDER = 'UPDATE_ORDER';
