export const ADD_REGULAR_CUSTOMER = 'ADD_REGULAR_CUSTOMER';
export const UPDATE_REGULAR_CUSTOMER = 'UPDATE_REGULAR_CUSTOMER';
export const REMOVE_REGULAR_CUSTOMER = 'REMOVE_REGULAR_CUSTOMER';
export const RESET_REGULAR_CUSTOMER_LIST = 'RESET_REGULAR_CUSTOMER_LIST';
