export default {
  plates: [
    {
      id: 'plat-du-jour',
      category: 'food',
      name: 'Plat du jour',
      price: 10.5,
    },
    {
      id: 'sandwich',
      category: 'food',
      name: 'Sandwich',
      price: 5.5,
    },
    {
      id: 'tarte-seule',
      category: 'food',
      name: 'Tarte salée<br><span class="small">(seule)</span>',
      price: 5,
    },
    {
      id: 'tarte-crudite',
      category: 'food',
      name: 'Tarte salée<br><span class="small">(+ crudités)</span>',
      price: 9.5,
    },
    {
      id: 'entree',
      category: 'food',
      name: 'Entrée',
      price: 3.5,
    },
    {
      id: 'soupe-petite',
      category: 'food',
      name: 'Soupe petite',
      price: 3.5,
    },
    {
      id: 'soupe-grande',
      category: 'food',
      name: 'Soupe grande',
      price: 5.5,
    },
    {
      id: 'dessert',
      category: 'food',
      name: 'Dessert',
      price: 3.5,
    },
    {
      id: 'cookie',
      category: 'food',
      name: 'Cookie',
      price: 2,
    },
    {
      id: 'eau',
      category: 'drink',
      name: 'Eau plate',
      price: 1.5,
    },
    {
      id: 'eau-gazeuse',
      category: 'drink',
      name: 'Eau gazeuse',
      price: 2,
    },
    {
      id: 'boisson-fraiche',
      category: 'drink',
      name: 'Soda - Jus de fruits',
      price: 3,
    },
    {
      id: 'biere-vin',
      category: 'drink',
      name: 'Bière - Vin',
      price: 2.5,
    },
    {
      id: 'cafe',
      category: 'drink',
      name: 'Café',
      price: 1.5,
    },
    {
      id: 'noisette',
      category: 'drink',
      name: 'Noisette',
      price: 1.8,
    },
    {
      id: 'boisson-chaude',
      category: 'drink',
      name: 'Thé - Latte - Cappuccino - Chocolat',
      price: 3,
    },
    {
      id: 'supplement',
      category: 'drink',
      name: 'Supplément',
      price: 0.2,
    },
    {
      id: 'petite-formule-sandwich',
      category: 'formule',
      name: '<strong>Petite</strong><br>Sandwich',
      baseItem: 'sandwich',
      size: 'small',
      price: 8.5,
    },
    {
      id: 'petite-formule-tarte',
      category: 'formule',
      name: '<strong>Petite</strong><br>Tarte',
      baseItem: 'tarte',
      size: 'small',
      price: 12,
    },
    {
      id: 'petite-formule-plat',
      category: 'formule',
      name: '<strong>Petite</strong><br>Plat du jour',
      baseItem: 'plat-du-jour',
      size: 'small',
      price: 13,
    },
    {
      id: 'grande-formule-sandwich',
      category: 'formule',
      name: '<strong>Grande</strong><br>Sandwich',
      baseItem: 'sandwich',
      size: 'big',
      price: 11.5,
    },
    {
      id: 'grande-formule-tarte',
      category: 'formule',
      name: '<strong>Grande</strong><br>Tarte',
      baseItem: 'tarte',
      size: 'big',
      price: 15,
    },
    {
      id: 'grande-formule-plat',
      category: 'formule',
      name: '<strong>Grande</strong><br>Plat du jour',
      baseItem: 'plat-du-jour',
      size: 'big',
      price: 16,
    },
  ],
};
